In [1]:
import numpy as np

In [2]:
matrix = np.array([[1, 2, 0, 4],
                  [0, 0, 0, 0],
                  [5, 6, 7, 8],
                  [0, 0, 0, 0]])

In [7]:
nonzero_rows = np.any(matrix != 0, axis=1)

In [8]:
nonzero_rows

array([ True, False,  True, False])

In [9]:
nonzero_cols = np.any(matrix != 0, axis=0)

In [10]:
nonzero_cols

array([ True,  True,  True,  True])

In [12]:
compacted_matrix = matrix[nonzero_rows][:, nonzero_cols]

In [13]:
compacted_matrix

array([[1, 2, 0, 4],
       [5, 6, 7, 8]])

In [15]:
first_positive_row = np.argmax(np.any(compacted_matrix > 0, axis=1))

In [16]:
first_positive_row

0

<h1>Исходная матрица</h1>

In [17]:
matrix

array([[1, 2, 0, 4],
       [0, 0, 0, 0],
       [5, 6, 7, 8],
       [0, 0, 0, 0]])

<h1>Уплотнённая матрица</h1>

In [18]:
compacted_matrix

array([[1, 2, 0, 4],
       [5, 6, 7, 8]])

<h1>Номер первой строки с положительным элементом/h1>

In [19]:
first_positive_row

0